### ISSUE TITLE
Rectifier bug

### ISSUE THREAD

**Issue by flamd** [flamd/examr-seii#87]
see comment: https://github.com/flamd/examr-seii/commit/e48cd396bfb251020749d302519dbd9a54ad0941

**Comment by fgaz** [comment]
Rectifier è case-sensitive

**Comment by flamd** [comment]
Le specifiche API per submission prevedono id con la i minuscola.  https://examr-seii-bold-develop.netlify.com/#tag/task-submission. Validator è case sensitive, e non permette gli id passati siano con la I maiuscola. quindi possiamo decidere tra:
* cambiare tutte le specifiche openAPI
* ad ogni richiesta ritradurre l'oggetto di input portando le 'I' di id da minuscole a maiuscole
* rendiamo rectifier case-insensitive

**Comment by fgaz** [comment]
> cambiare tutte le specifiche openAPI

cambiare solo quelle di submission. la maggior parte degl id nell'openapi non fiinisce nemmeno per `Id` (`creator`, `answer`...)

**Comment by fgaz** [comment]
ma se vuoi renderlo case-insensitive fai pure, basta che funzioni
